cart/urls.py
from django.urls import path
from cart.views import cart_detail, cart_add, cart_remove

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('', cart_detail, name='cart_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('mainapp.urls', namespace='mainapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp.views import ItemListView, ItemDetailView, BuyItemView

app_name = 'mainapp'

urlpatterns = [
    path('item/<int:pk>/', ItemDetailView.as_view(), name='item_detail'),
    path('buy/<int:pk>/', BuyItemView, name='buy_item'),
    path('buy/', BuyItemView, name='buy_item'),
    path('', ItemListView.as_view(), name='item_list'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]

class CartAddProductForm(forms.Form):
	# quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
	quantity = forms.IntegerField()
	update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from mainapp.models import Item
from cart.cart import Cart
from cart.forms import CartAddProductForm



def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Item, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        if cd['quantity'] == 0:
            cart_remove(request, product_id)
        else:
            cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Item, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    if cart:
        for item in cart:
            item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'update': True})
        return render(request, 'cart/detail.html', locals())
    else:
        return redirect('mainapp:item_list')

templates/cart/detail.html
{% extends '../index.html' %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block title %} Items in the cart {% endblock %}
{% block content %}
    <div class="app-main__outer"> 
        {% if messages %}
            {% for message in messages %}
                <div id="toast-container" class="toast-bottom-right">
                    <div class="toast toast-{{ message.tags }}" aria-live="assertive" style="opacity: 100;">
                        <div class="toast-message">{{ message }}</div>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
        <div class="app-main__inner">
            <div class="row">
                <div class="col-lg-12">
                    <div class="main-card mb-3 card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <div id="example_wrapper" class="dataTables_wrapper no-footer">
                                    <table id="example" class="mb-0 table table-bordered table-hover display dataTable no-footer" style="width:100%" aria-describedby="example_info">
                                        <thead>
                                            <tr>
                                                <th class="sorting sorting_asc" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-sort="ascending">#</th>
                                                <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1">Nomi</th>
                                                <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1">Narxi</th>
                                                <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1">Soni</th>
                                                <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1">Jami</th>
                                                <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1"></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for item in cart %}
                                            <tr class="even">
                                                <td>{{forloop.counter}}</td>
                                                <td><a href="{{ item.product.get_absolute_url  }}">{{item.product.name}}</a></td>
                                                <td><i class="fa fa-dollar-sign fa-w-20"></i>{{item.price|intcomma}} USD</td>
                                                <td>
                                                <form action="{% url 'cart:cart_add' item.product.id %}" method="post">
                                                    <input name="quantity" id="id_quantity" value="{{item.update_quantity_form.quantity.value}}"/>
                                                    <button type="submit" class="btn-shadow btn btn-info">Save</button>
                                                    {% csrf_token %}
                                                </form>
                                                </td>
                                                <td><i class="fa fa-dollar-sign fa-w-20"></i>{{item.total_price|intcomma}} USD</td>
                                                <td>
                                                    <a href="{% url 'cart:cart_remove' item.product.id %}" class="text-center">
                                                        <button type="button" class="btn-shadow btn btn-danger">
                                                            <span class="btn-icon-wrapper pr-2 opacity-7">
                                                            <i class="fa fa-trash fa-w-20"></i>
                                                            </span>
                                                            Remove
                                                        </button>
                                                    </a>
                                                </td>
                                            </tr>
                                            {% empty %}
                                            <tr><td colspan="6" class="text-center">Cart is empty</td></tr>
                                            {% endfor %}
                                            <tr class="total text-center">
                                                <td colspan="2" rowspan="2">Total price:</td>
                                                <td colspan="2">
                                                    <b>
                                                        <i class="fa fa-dollar-sign fa-w-20"></i> 
                                                        {{ cart.get_total_price_in_usd|floatformat:2 }} USD 
                                                    </b> 
                                                    <a href="" class="variant btn-shadow btn btn-info" data-id="usd">Pay in USD</a>
                                                </td>
                                                <td colspan="2">
                                                    <b>
                                                        <i class="fa fa-euro-sign fa-w-20"></i> 
                                                        {{ cart.get_total_price_in_eur|floatformat:2 }} EUR 
                                                    </b> 
                                                    <a href="" class="variant btn-shadow btn btn-info" data-id="eur">Pay in EUR</a>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block domready %}
    $('a.variant').click(function(e){
        e.preventDefault();
        button = $(this);
        currency = $(this).data('id');
        console.log(currency);
        $.ajax({
            url: '{% url "mainapp:buy_item" %}',
            type: 'post',
            data: {
                ans: currency,
            },
            success: function (res) {
                var stripe = Stripe('pk_test_51M7BoYEQQc02GODdwv7z49y6r8F8gwQDx9uMcWbZuanpQjsuNUr3o8mWcQeZJDdKNK8JBZA6xhvWWb5IiQhCtjBR00QC224rjq');
                window.location.href = res['session_id'];
                stripe.redirectToCheckout({ sessionId: res['session_id'] });
            },
            error:function (error) {
                console.log("error");
                console.log(error);
            }
        })
    });

{% endblock domready %}