cart/urls.py
from django.urls import path
from cart.views import cart_detail, cart_add, cart_remove

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('', cart_detail, name='cart_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('mainapp.urls', namespace='mainapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp.views import ItemListView, ItemDetailView, BuyItemView

app_name = 'mainapp'

urlpatterns = [
    path('item/<int:pk>/', ItemDetailView.as_view(), name='item_detail'),
    path('buy/<int:pk>/', BuyItemView, name='buy_item'),
    path('buy/', BuyItemView, name='buy_item'),
    path('', ItemListView.as_view(), name='item_list'),
]

templates/index.html
{% load static %}
{% load humanize %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no"/>
    <!-- Disable tap highlight on IE -->
    <meta name="msapplication-tap-highlight" content="no">
    <link href="{% static 'main.87c0748b313a1dda75f5.css' %} " rel="stylesheet">
  </head>
  {% block jscode %}{% endblock jscode %}
  <body>
    <div class="app-container app-theme-white body-tabs-shadow fixed-header fixed-sidebar">
      <div class="app-header header-shadow">
        <div class="app-header__logo">
          <div class="logo-src"></div>
          <div class="header__pane ml-auto">
            <div>
              <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                <span class="hamburger-box">
                  <span class="hamburger-inner"></span>
                </span>
              </button>
            </div>
          </div>
        </div>
        {% if messages %}
          {% for message in messages %}
            <div id="toast-container" class="toast-bottom-right">
              <div class="toast toast-{{ message.tags }}" aria-live="assertive" style="opacity: 100;">
                <div class="toast-message">{{ message }}</div>
              </div>
            </div>
          {% endfor %}
        {% endif %}
        <div class="app-header__mobile-menu">
          <div>
            <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
              <span class="hamburger-box">
                <span class="hamburger-inner"></span>
              </span>
            </button>
          </div>
        </div>
        <div class="app-header__menu">
          <span>
            <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
              <span class="btn-icon-wrapper">
                <i class="fa fa-ellipsis-v fa-w-6"></i>
              </span>
            </button>
          </span>
        </div>
        <div class="app-header__content">
          <div class="app-header-right">
            <div class="header-dots">
              <div class="dropdown">
                <!-- Savatcha -->
                {% with total_items=cart|length %}
                {% if cart|length >= 0 %}
                  <a href="{% url 'cart:cart_detail' %}">
                    <button class="mb-2 mr-2 btn btn-info font-icon-lg">
                      <i class=" fa fa-shopping-cart icon-gradient bg-love-kiss"> </i>
                      <span class="badge badge-pill badge-light"></span>
                    </button>
                  </a>
                {% endif %}
                {% endwith %}
              </div>
            </div>
            <div class="header-btn-lg pr-0">
              <div class="widget-content p-0">
                <div class="widget-content-wrapper">
                  <div class="widget-content-left">
                    <div class="btn-group">
                      <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="p-0 btn">
                        <img width="42" class="rounded-circle" src=" {% static 'assets/images/avatars/2.jpg' %}" alt="">
                        <i class="fa fa-angle-down ml-2 opacity-8"></i>
                      </a>
                      <div tabindex="-1" role="menu" aria-hidden="true" class="rm-pointers dropdown-menu-lg dropdown-menu dropdown-menu-right">
                        <div class="dropdown-menu-header">
                          <div class="dropdown-menu-header-inner bg-info">
                            <div class="menu-header-image opacity-2" style="background-image: url({% static 'assets/images/dropdown-header/city3.jpg' %} );"></div>
                            <div class="menu-header-content text-left">
                              <div class="widget-content p-0">
                                <div class="widget-content-wrapper">
                                  <div class="widget-content-left mr-3">
                                    <img width="42" class="rounded-circle" src="{% static 'assets/images/avatars/2.jpg' %}" alt="">
                                  </div>
                                  <div class="widget-content-left">
                                    <div class="widget-heading">
                                        Ravshan Ismoilov
                                    </div>
                                  </div>
                                  <div class="widget-content-right mr-2">
                                    <a href="#" class="btn-pill btn-shadow btn-shine btn btn-focus">Logout
                                    </a>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="widget-content-left ml-3 header-user-info">
                    <div class="widget-heading">
                      Ravshan Ismoilov
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        </div>
        <div class="ui-theme-settings">
          <button type="button" id="TooltipDemo" class="btn-open-options btn btn-warning">
              <i class="fa fa-cog fa-w-16 fa-spin fa-2x"></i>
          </button>
        </div>
        <div class="app-main">
          <div class="app-sidebar sidebar-shadow">
          <div class="app-header__logo">
            <div class="logo-src"></div>
            <div class="header__pane ml-auto">
              <div>
                <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                  <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                  </span>
                </button>
              </div>
            </div>
          </div>
          <div class="app-header__mobile-menu">
            <div>
              <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                <span class="hamburger-box">
                  <span class="hamburger-inner"></span>
                </span>
              </button>
            </div>
          </div>
          <div class="app-header__menu">
            <span>
              <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                <span class="btn-icon-wrapper">
                  <i class="fa fa-ellipsis-v fa-w-6"></i>
                </span>
              </button>
            </span>
          </div>
          <div class="">
            <div class="app-sidebar__inner">
                <ul class="vertical-nav-menu">
                  <li class="app-sidebar__heading">Menu</li>
                  <li>
                    <a href="{% url 'mainapp:item_list' %}">
                        <i class="metismenu-icon pe-7s-home"></i>
                        Home page
                    </a>
                  </li>
                  <li>
                    <a href="{% url 'cart:cart_detail' %}">
                      <i class="metismenu-icon pe-7s-cart"></i>
                      Cart detail
                    </a>
                  </li>
                </ul>
            </div>
          </div>
        </div>
      
        {% block content %}{% endblock %}

    </div>
  </div>
  <div class="app-drawer-overlay d-none animated fadeIn"></div>
    
  <script type="text/javascript" src="{% static 'assets/scripts/main.87c0748b313a1dda75f5.js' %} "></script>
  <!-- AJAX -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/js.cookie.min.js' %}"></script>
  <script src="https://js.stripe.com/v3/"></script>

  <script>
    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings)
        {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain)
                { xhr.setRequestHeader("X-CSRFToken", csrftoken); }
        }
    });

    $(document).ready(function(){
        {% block domready %}{% endblock domready %}
    });
  </script>
  </body>
</html>
{% block modal %}{% endblock modal %}

templates/item_detail.html
<html>
  <head>
    <title>Buy {{item.name}}</title>
  </head>
  <body>
    <h1>Name: {{item.name}}</h1>
    <p>Description: {{item.description}}</p>
    <p>Price: ${{item.price}}</p>
    <button id="buy-button">Buy</button>
    <script type="text/javascript">
      var stripe = Stripe('pk_test_51M7BoYEQQc02GODdwv7z49y6r8F8gwQDx9uMcWbZuanpQjsuNUr3o8mWcQeZJDdKNK8JBZA6xhvWWb5IiQhCtjBR00QC224rjq');
      var buyButton = document.getElementById('buy-button');
      buyButton.addEventListener('click', function() {
        console.log('123')
        // Create a new Checkout Session using the server-side endpoint 
        // Redirect to Stripe Session Checkout
        fetch('/buy/{{item.pk}}', {method: 'GET'})
        .then(response => return response.json())
        .then(session => stripe.redirectToCheckout({ sessionId: session.id }))
      });
    </script>
  </body>
</html>

templates/item_list.html
{% extends 'index.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} All items {% endblock %}

{% block content %}
    <div class="app-main__outer">
        <div class="app-main__inner">
            <div class="app-page-title">
                <div class="page-title-wrapper">
                    <div class="page-title-heading">
                        <div>
                            <div class="page-title">
                                <a href="#">
                                    <button class="mb-2 mr-2 btn btn-primary">Count<span class="badge badge-pill badge-light">{{ items.count }}</span></button>
                                </a> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="main-card mb-3 card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <div id="example_wrapper" class="dataTables_wrapper no-footer">
                                    <table id="example" class="mb-0 table table-bordered table-hover display dataTable no-footer" style="width:100%" aria-describedby="example_info">
                                        <thead>
                                            <tr>
                                                <th class="sorting sorting_asc" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-sort="ascending">#</th>
                                                <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1">Name</th>
                                                <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1">Description</th>
                                                <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1">Price</th>
                                                <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1"></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {%for product in items %}
                                                <tr class="odd">
                                                    <td class="sorting_1 sorting_2">{{forloop.counter}}</td>
                                                    <td><a href="{{ product.get_absolute_url  }}">{{product.name}}</a></td>
                                                    <td>{{product.description|slice:"25"}}...</td>
                                                    <td>{{product.price}} {{product.get_currency_display}}</td>
                                                    <td>
                                                        <button type="button" class="btn-shadow btn btn-primary" data-toggle="modal" data-target=".bd-example-modal-lg{{product.id}}">
                                                            <span class="btn-icon-wrapper pr-2 opacity-7">
                                                                <i class="fa fa-cart-plus fa-w-20"></i>
                                                            </span>
                                                            Add to cart
                                                        </button>
                                                    </td>
                                                </tr>
                                            {% empty %}
                                                <tr><h4>Items not found!!!</h4></tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block modal %}
    {% for product in items %}
        <div class="modal fade bd-example-modal-lg{{product.id}}" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" style="display: none;" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle"> Select the item quantity. </h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post" class="m-2">
                        <div class="modal-body">
                            {% csrf_token %}
                            {{ form|crispy }}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-info">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock modal %}